import { useEffect, useState } from "react";
import { getCollection, COLLECTIONS } from "@nayeem/firebase";
import { GlowCard, Loader } from "@nayeem/ui";

interface Counts { projects:number; featuredProjects:number; research:number; articles:number; certificates:number; skills:number; techStack:number; messages:number; unreadMessages:number; }
export function Dashboard(){
  const [counts,setCounts]=useState<Counts|null>(null); const [error,setError]=useState("");
  useEffect(()=>{(async()=>{try{const [projects,research,articles,certificates,skills,techStack,messages]=await Promise.all([getCollection<any>(COLLECTIONS.projects),getCollection<any>(COLLECTIONS.research),getCollection<any>(COLLECTIONS.articles),getCollection<any>(COLLECTIONS.certificates),getCollection<any>(COLLECTIONS.skills),getCollection<any>(COLLECTIONS.techStack),getCollection<any>(COLLECTIONS.messages)]);setCounts({projects:projects.length,featuredProjects:projects.filter(p=>p.featured).length,research:research.length,articles:articles.length,certificates:certificates.length,skills:skills.length,techStack:techStack.length,messages:messages.length,unreadMessages:messages.filter(m=>m.status==="unread").length});}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard data.");}})()},[]);
  if(error)return <GlowCard className="border-red-400/30"><p className="font-semibold text-red-300">Dashboard could not load.</p><p className="mt-2 text-sm text-foreground-muted">{error}</p><p className="mt-3 text-xs text-foreground-faint">Check the Firebase environment variables and make sure your signed-in UID exists in Firestore at admins/&lt;UID&gt;.</p></GlowCard>;
  if(!counts)return <Loader label="LOADING DASHBOARD…"/>;
  const cards=[{label:"Projects",value:counts.projects},{label:"Featured Projects",value:counts.featuredProjects},{label:"Research",value:counts.research},{label:"Articles",value:counts.articles},{label:"Certificates",value:counts.certificates},{label:"Skills",value:counts.skills},{label:"Tech Stack",value:counts.techStack},{label:"Messages",value:counts.messages},{label:"Unread Messages",value:counts.unreadMessages}];
  return <div><p className="font-mono text-xs tracking-[0.3em] text-accent-cyan">OVERVIEW</p><h1 className="mt-2 font-display text-3xl font-bold">Dashboard</h1><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(c=><GlowCard key={c.label}><p className="font-mono text-[11px] tracking-widest text-foreground-muted">{c.label.toUpperCase()}</p><p className="mt-2 font-display text-3xl font-bold">{c.value}</p></GlowCard>)}</div></div>
}
