import { useEffect, useMemo, useState } from "react";
import { createDocument, deleteDocument, getCollection, getDocument, setDocument, updateDocument, orderBy } from "@nayeem/firebase";
import { Button, EmptyState, GlowCard, Loader } from "@nayeem/ui";
import { Pencil, Plus, RefreshCw, Save, Trash2, X } from "lucide-react";
import { CloudinaryUpload } from "./CloudinaryUpload";

export type FieldConfig = { key: string; label: string; type?: "text" | "textarea" | "number" | "boolean" | "url" | "date" | "array" | "select" | "image"; placeholder?: string; options?: string[]; help?: string };
type CmsRecord = Record<string, any> & { id?: string };
const inputClass = "mt-1 w-full rounded-lg border border-base-border bg-base-black px-3 py-2 text-sm outline-none focus:border-accent-cyan";
function getPath(obj: CmsRecord, path: string) { return path.split(".").reduce((value: any, key) => value?.[key], obj); }
function setPath(obj: CmsRecord, path: string, value: any): CmsRecord {
  const parts = path.split("."); const next = { ...obj }; let cursor: any = next;
  parts.slice(0, -1).forEach((part) => { cursor[part] = { ...(cursor[part] ?? {}) }; cursor = cursor[part]; });
  cursor[parts[parts.length - 1]] = value; return next;
}

function Field({ field, value, onChange }: { field: FieldConfig; value: any; onChange: (value: any) => void }) {
  const type = field.type ?? "text";
  const label = field.label.toUpperCase();
  if (type === "boolean") return <label className="flex items-center gap-3 rounded-lg border border-base-border bg-base-near p-3"><input type="checkbox" checked={Boolean(value)} onChange={(e) => onChange(e.target.checked)} /><span><span className="text-sm font-semibold">{field.label}</span>{field.help && <small className="mt-1 block text-foreground-muted">{field.help}</small>}</span></label>;
  if (type === "select") return <label className="block"><span className="font-mono text-[11px] tracking-widest text-foreground-muted">{label}</span><select className={inputClass} value={String(value ?? "")} onChange={(e) => onChange(e.target.value)}>{(field.options ?? []).map((option) => <option key={option} value={option}>{option}</option>)}</select>{field.help && <small className="mt-1 block text-foreground-muted">{field.help}</small>}</label>;
  if (type === "array") return <label className="block"><span className="font-mono text-[11px] tracking-widest text-foreground-muted">{label}</span><textarea className={inputClass} rows={4} value={Array.isArray(value) ? value.join("\n") : ""} placeholder={field.placeholder ?? "One item per line"} onChange={(e) => onChange(e.target.value.split("\n").map((v) => v.trim()).filter(Boolean))} />{field.help && <small className="mt-1 block text-foreground-muted">{field.help}</small>}</label>;
  if (type === "image") return <CloudinaryUpload value={value?.url ?? ""} label={field.label} folder="portfolio/cms" onChange={onChange} />;
  const onInput = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(type === "number" ? Number(e.target.value) : e.target.value);
  return <label className="block"><span className="font-mono text-[11px] tracking-widest text-foreground-muted">{label}</span>{type === "textarea" ? <textarea className={inputClass} rows={4} value={String(value ?? "")} placeholder={field.placeholder} onChange={onInput} /> : <input className={inputClass} value={String(value ?? "")} placeholder={field.placeholder} type={type === "url" ? "url" : type === "number" ? "number" : type === "date" ? "date" : "text"} onChange={onInput} />}{field.help && <small className="mt-1 block text-foreground-muted">{field.help}</small>}</label>;
}

function Modal({ title, fields, initial, onClose, onSave, saving }: { title: string; fields: FieldConfig[]; initial: CmsRecord; onClose: () => void; onSave: (data: CmsRecord) => void; saving: boolean }) {
  const [form, setForm] = useState<CmsRecord>(initial);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 sm:p-6"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl border border-base-border bg-base-near p-5 sm:p-6"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold">{title}</h2><button onClick={onClose}><X size={18} /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{fields.map((field) => <div key={field.key} className={field.type === "textarea" || field.type === "array" || field.type === "boolean" || field.type === "image" ? "sm:col-span-2" : ""}><Field field={field} value={getPath(form, field.key)} onChange={(value) => setForm((current) => setPath(current, field.key, value))} /></div>)}</div><div className="mt-6 flex justify-end gap-3"><Button variant="ghost" onClick={onClose}>CANCEL</Button><Button onClick={() => onSave(form)} disabled={saving}><Save size={15} /> {saving ? "SAVING…" : "SAVE"}</Button></div></div></div>;
}

export function CollectionAdminPage({ title, collection, fields, defaults = {}, orderKey = "order" }: { title: string; collection: string; fields: FieldConfig[]; defaults?: CmsRecord; orderKey?: string }) {
  const [items, setItems] = useState<CmsRecord[] | null>(null); const [editing, setEditing] = useState<CmsRecord | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const safeCollection = typeof collection === "string" ? collection.trim() : "";
  const load = async () => { setError(""); if (!safeCollection) { setItems([]); setError("CMS collection path is empty. Please restart the admin dev server after updating the project."); return; } try { setItems(await getCollection<CmsRecord>(safeCollection, orderKey ? [orderBy(orderKey, "asc")] : [])); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load data."); setItems([]); } };
  useEffect(() => { void load(); }, [safeCollection, orderKey]);
  const empty = useMemo(() => ({ ...defaults }), [defaults]);
  const save = async (form: CmsRecord) => { setSaving(true); setError(""); try { if (!safeCollection) throw new Error("CMS collection path is empty."); if (form.id) { const { id, ...rest } = form; await updateDocument(safeCollection, id, rest); } else { const { id: _id, ...rest } = form; await createDocument(safeCollection, rest); } setEditing(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Save failed."); } finally { setSaving(false); } };
  const remove = async (id: string) => { if (!confirm(`Delete this ${title.toLowerCase()} item?`)) return; try { if (!safeCollection) throw new Error("CMS collection path is empty."); await deleteDocument(safeCollection, id); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Delete failed."); } };
  return <div><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-xs tracking-[0.3em] text-accent-cyan">CMS / CONTENT</p><h1 className="mt-2 font-display text-3xl font-bold">{title}</h1><p className="mt-1 text-sm text-foreground-muted">Create, edit and delete {title.toLowerCase()} content.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="rounded-lg border border-base-border p-2 hover:border-accent-cyan" title="Reload"><RefreshCw size={17} /></button><Button onClick={() => setEditing(empty)}><Plus size={14} /> NEW</Button></div></div>{error && <GlowCard className="mt-5 border-red-400/30"><p className="text-sm text-red-300">{error}</p></GlowCard>}{!items && <Loader label={`LOADING ${title.toUpperCase()}…`} />}{items && items.length === 0 && <div className="mt-8"><EmptyState title={`NO ${title.toUpperCase()} YET`} hint="Click New to create the first item." /></div>}<div className="mt-8 space-y-3">{(items ?? []).map((item, index) => <GlowCard key={String(item.id)} className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="font-display font-semibold">{String(item.title ?? item.name ?? item.role ?? item.organization ?? item.filename ?? `Item ${index + 1}`)}</p><p className="mt-1 line-clamp-2 text-sm text-foreground-muted">{String(item.description ?? item.abstract ?? item.tagline ?? item.category ?? item.url ?? "Managed content")}</p><p className="mt-2 font-mono text-[10px] text-foreground-faint">#{index + 1} · {item.id}</p></div><div className="flex shrink-0 gap-3"><button onClick={() => setEditing(item)} className="text-foreground-muted hover:text-foreground" title="Edit"><Pencil size={16} /></button><button onClick={() => void remove(String(item.id))} className="text-foreground-muted hover:text-red-400" title="Delete"><Trash2 size={16} /></button></div></GlowCard>)}</div>{editing && <Modal title={editing.id ? `Edit ${title}` : `New ${title}`} fields={fields} initial={editing} onClose={() => setEditing(null)} onSave={save} saving={saving} />}</div>;
}

export function SingleDocumentAdminPage({ title, collection, docId, fields, defaults }: { title: string; collection: string; docId: string; fields: FieldConfig[]; defaults: CmsRecord }) {
  const [form, setForm] = useState<CmsRecord>(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const data = await getDocument<CmsRecord>(collection, docId); setForm(data ? { ...defaults, ...data } : { ...defaults }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load document."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [collection, docId]);
  const save = async () => { setSaving(true); setMessage(""); setError(""); try { const { id: _id, ...rest } = form; await setDocument(collection, docId, rest); setMessage("Saved successfully."); } catch (e) { setError(e instanceof Error ? e.message : "Save failed."); } finally { setSaving(false); } };
  return <div><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-xs tracking-[0.3em] text-accent-cyan">CMS / SINGLETON</p><h1 className="mt-2 font-display text-3xl font-bold">{title}</h1><p className="mt-1 text-sm text-foreground-muted">Edit the live portfolio content stored in Firestore.</p></div><button onClick={() => void load()} className="rounded-lg border border-base-border p-2 hover:border-accent-cyan" title="Reload"><RefreshCw size={17} /></button></div><GlowCard className="mt-8 max-w-4xl">{loading ? <Loader label="LOADING…" /> : <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <div key={field.key} className={field.type === "textarea" || field.type === "array" || field.type === "boolean" || field.type === "image" ? "sm:col-span-2" : ""}><Field field={field} value={getPath(form, field.key)} onChange={(value) => setForm((current) => setPath(current, field.key, value))} /></div>)}</div>{message && <p className="text-sm text-accent-green">{message}</p>}{error && <p className="text-sm text-red-300">{error}</p>}<Button onClick={() => void save()} disabled={saving}><Save size={16} /> {saving ? "SAVING…" : "SAVE CHANGES"}</Button></div>}</GlowCard></div>;
}
