export const COLLECTIONS = {
  profile: "profile",
  about: "about",
  skills: "skills",
  techStack: "techStack",
  experience: "experience",
  certificates: "certificates",
  projects: "projects",
  articles: "articles",
  research: "research",
  services: "services",
  messages: "messages",
  github: "github",
  socialLinks: "socialLinks",
  settings: "settings",
  media: "media",
  admins: "admins",
} as const;
